default:
  image: moby/buildkit:rootless

variables:
  BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  VERSION: "2.1.4"

docker-build:
  stage: build
  before_script:
    - |
      mkdir ~/.docker
      auth=$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)
      echo "{\"auths\": {\"$CI_REGISTRY\": {\"auth\": \"$auth\"}}}" > ~/.docker/config.json
  script:
    - |
        TMPDIR=/dev/shm buildctl-daemonless.sh build \
            --frontend=dockerfile.v0 \
            --opt platform=linux/arm64,linux/aarch64.linux/amd64 \
            --local context=. \
            --local dockerfile=. \
            --import-cache type=registry,ref=$CI_REGISTRY_IMAGE:$VERSION \
            --export-cache type=inline \
            --output type=image,name=$CI_REGISTRY_IMAGE:$VERSION,push=true
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

