entities:
- application: absent
  chars: null
  dsuid: apartmentAbsents
  entity_id: 6bc23675c24a38eba40060e7155fef3500.switch
  name: Abwesend
  service: switch
  support: null
  zone: Apartment
token: d2bb3b9ea966eda61c19cae31ecf5d2a8c12d68ccce2032f33a36502fe446d43
zones: []
